plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.notiforwarder'
    compileSdk 33

    defaultConfig {
        applicationId "com.example.notiforwarder"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'com.google.mlkit:text-recognition:16.0.0'
}